storage:
 value: default
 wizard:
   name: "Storage Configuration"
   kind: cluster_storage

pytorch_version:
  value: "0.3.1"
  wizard:
    name: "PyTorch version"
    kind: select
    options:
    - "0.3.1"

python_version:
  value: "2"
  wizard:
    name: "Python version"
    kind: select
    options:
    - "2"
    - "3"

src:
  value: https://github.com/kuberlab/pytorch-examples
  wizard:
    name: "Source Code"
    kind: git

dataset:
 value: ''
 version: ''
 workspace: ''
 wizard:
   name: "Dataset configuration"
   kind: dataset

# Pip packages may be specified here in format that pip accepts.
packages: []
