storage:
 value: default
 wizard:
   name: "Storage Configuration"
   kind: cluster_storage

src: https://github.com/kuberlab-catalog/pytorch
src_path: pytorch/src

data_path: data

pytorch_versiob:
  value: "0.2.0"
  wizard:
    name: "PyTorch version"
    kind: select
    options:
    - "0.2.0"

python_version:
  value: "2"
  wizard:
    name: "Python version"
    kind: select
    options:
    - "2"
    - "3"

serving_port: 9000

packages:
 - "git+https://github.com/kuberlab/python-mlboardclient.git"
