storage:
 value: default
 wizard:
   name: "Storage Configuration"
   kind: cluster_storage

pytorch_version:
  value: "1.9.0"
  wizard:
    name: "PyTorch version"
    kind: select
    options:
    - "1.3.1"
    - "1.4.0"
    - "1.5.0"
    - "1.7.1"
    - "1.8.1"
    - "1.9.0"

tensorboard:
  value: true
  wizard:
    name: Install Tensorboard
    kind: boolean

src:
  value: https://github.com/kuberlab/pytorch-examples
  wizard:
    name: "Source Code"
    kind: git

installExamples:
  value: false
  wizard:
    name: Add examples
    kind: boolean

dataset:
 value: 'mnist'
 version: '1.0.0'
 workspace: 'kuberlab-demo'
 wizard:
   name: "Dataset configuration"
   kind: dataset

# Pip packages may be specified here in format that pip accepts.
packages: []
